- hosts: docker
  become: true
  roles: 
  - docker

- hosts: jenkins
  become: true
  roles: 
  - jenkins

- hosts: nginx
  become: true
  roles:
  - nginx 

- hosts: aws
  become: true
  roles:
  - aws

- hosts: kube
  become: true
  roles:
  - kube 
