version: "3.7"
services:
  frontend:
    build: ./frontend
    image: frontend:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  backend:
    build: ./backend
    image: backend:latest
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
      DATABASE_URI: mysql+pymysql://admin:root1234@terraform-20201120104301716100000001.cr9zze1q6zyi.eu-west-1.rds.amazonaws.com/users
      TEST_DATABASE_URI: mysql+pymysql://admin:root1234@terraform-20201120104301718800000002.cr9zze1q6zyi.eu-west-1.rds.amazonaws.com:3306/testdb
