---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-app
  labels: 
    app: project
spec:
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: pyapp-container
        image: sherazshahid017/project-be:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: database-uri
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: secret-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fe
  labels:
    app: front
spec:
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: pyapp-container
        image: sherazshahid017/project-fe:latest
        ports:
        - containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels: 
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
