apiVersion: v1
kind: Secret
metadata:
  name: secretsql
  labels:
    app: sql
type: Opaque
stringData:
        database-uri: 'mysql+pymysql://admin:root1234@terraform-20201121105938104200000002.cr9zze1q6zyi.eu-west-1.rds.amazonaws.com:3306/users'
  secret-key: 'dsnbdsf'
