apiVersion: v1
kind: Secret
metadata:
  name: secretsql
  labels:
    app: sql
type: Opaque
stringData:
  database-uri: 'mysql+pymysql://admin:root1234@trio-db.cr9zze1q6zyi.eu-west-1.rds.amazonaws.com/testdb'
