apiVersion: v1
kind: Service
metadata:
  name: py-app-back-serv-ip
  labels:
    app: back
spec:
  selector:
    app: back
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: py-app-front-serv-ip
  labels:
    app: front
spec:
  selector:
    app: front
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
